 let question =[
     {question:"Prefix notation is alsow known as",
     choiceOne:"Reverse Polish Notation",
     choiceTwo:"Reverse Notation",
     choiceThree:"Polish Reverse Notation",
     choicefour:"Polish Notation",
     awnser:"4"
    },
    {question:"What data structure is used for breadth first traversal of a graph?",
    choiceOne:"queue",
    choiceTwo:"stack",
    choiceThree:"list",
    choicefour:"none of the above",
    awnser:"1"
   },
   {question:"Find the odd out",
   choiceOne:" Prim's Minimal Spanning Tree Algorithm",
   choiceTwo:"Kruskal's Minimal Spanning Tree Algorithm",
   choiceThree:"Floyd-Warshall's All pair shortest path Algorithm",
   choicefour:"Dijkstra's Minimal Spanning Tree Algorithm",
   awnser:"3"
  },
  {question:"Which of the following algorithm is not stable?",
  choiceOne:"Bubble Sort",
  choiceTwo:"Quick Sort",
  choiceThree:"Merge Sort",
  choicefour:"Insertion Sort",
  awnser:"2"
 },
 {question:"After each iteration in bubble sort",
 choiceOne:"at least one element is at its sorted position.",
 choiceTwo:"one less comparison is made in the next iteration.",
 choiceThree:"Both A & B are true.",
 choicefour:"Neither A or B are true.",
 awnser:"1"
},
{
question:"Linked list search complexity is",
choiceOne:"Ο(1)",
choiceTwo:"Ο(n)",
choiceThree:" Ο(log n)",
choicefour:"Ο(log log n)",
awnser:"2"
},
{question:"Program with highest run-time complexity is",
choiceOne:" Tower of Hanoi",
choiceTwo:"Fibonacci Series",
choiceThree:"Prime Number Series",
choicefour:"None of the above",
awnser:"1"
}, 
{question:"The following sorting algorithms maintain two sub-lists, one sorted and one to be sorted",
choiceOne:"Selection Sort",
choiceTwo:"Insertion Sort",
choiceThree:"Merge Sort",
choicefour:"both A &am; B",
awnser:"4"
},
{question:"In conversion from prefix to postfix using stack data-structure, if operators and operands are pushed and popped exactly once, then the run-time complexity is",
choiceOne:"Ο(1)",
choiceTwo:"Ο(n)",
choiceThree:"Ο(log n)",
choicefour:"Ο(n2)",
awnser:"2"
},
{question:"Which of the following data structures falls under the category of a 'dictionary'?",
choiceOne:"Hash table",
choiceTwo:"Hash",
choiceThree:"Tree",
choicefour:"Linked list",
awnser:"1"
},
{question:"When using a heap, which function will give you the parent of the entry with index i?",
choiceOne:"Decimal division, i / 2",
choiceTwo:"Integer division, i / 2",
choiceThree:"Multiplication, i * 2",
choicefour:"Multiplication, i * 2 + 1",
awnser:"2"
},
{question:"A vector (an indexed, growable list) would most likely be implemented on top of which of these structures?",
choiceOne:"Hash table",
choiceTwo:"Stack",
choiceThree:"Tree",
choicefour:"Linked list",
awnser:"4"
},
{question:"If you have an empty stack that can contain letters, and you push (in order) these letters onto it, what order will they be in when you pop them off? 't' 'a' 'p'",
choiceOne:"t' 'a' 'p'",
choiceTwo:"'p' 'a' 't'",
choiceThree:"'a' 'p' 't'",
choicefour:"There is no way to tell",
awnser:"2"
},
{question:"If you have a empty queue that can contain letters, and you enqueue (in order) these letters into it, what order will they be in when you dequeue them? 'm' 'a' 'r'",
choiceOne:" 'r' 'a' 'm'",
choiceTwo:"'m' 'a' 'r'",
choiceThree:"'a' 'r' 'm'",
choicefour:"There is no way to tell",
awnser:"2"
},
{question:"Which of the following could best be described by the graph structure?",
choiceOne:"Roads connecting cities",
choiceTwo:"A GUI (Graphical User Interface)",
choiceThree:" Algebraic problems",
choicefour:" Given a word, finding its definition",
awnser:"1"
},
{question:"If you have a sorted, balanced binary tree with 15 elements in it, how many steps, maximum, will it take you to decide whether an element is present in the tree?",
choiceOne:"Three",
choiceTwo:"Depends on the computer",
choiceThree:"Fifteen",
choicefour:"Four",
awnser:"4"
},
{question:"If you wanted to make sure that the close-parenthesis (the ')' character) matches the open-parenthesis (the '(' character) in a mathematical expression, which data structure could help you?",
choiceOne:"Queue",
choiceTwo:"Hash table",
choiceThree:"Tree",
choicefour:"Stack",
awnser:"4"
},
{question:"Which of these is true about a set?",
choiceOne:"All of these",
choiceTwo:"The elements are kept in order",
choiceThree:"There are no duplicates",
choicefour:"They can only hold numbers",
awnser:"3"
},
{question:"Modern filesystems, like ReiserFS and XFS, use which structure to organize their data for efficient access?",
choiceOne:" Lists",
choiceTwo:"B-Trees",
choiceThree:"B+Trees",
choicefour:"Tables",
awnser:"3"
},
{question:"what is not a programming languages",
choiceOne:"python",
choiceTwo:"Groovy",
choiceThree:"Bertrand",
choicefour:"Boosque",
awnser:"4"
}
 ]

 export default  question